name: PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/_run-tests.yml

  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Detect secrets
        uses: alphagov/pay-ci/actions/detect-secrets@master
